var fullname = 'Henry Pham';
var isCool = true;
var totalPets = 1;
var unknown = null;
var never = undefined;
console.log('value of fullname:', fullname);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('value of unknown:', unknown);
console.log('value of never:', never);
console.log('typeof fullname:', typeof fullname);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
console.log('typeof unknown:', typeof unknown);
console.log('typeof never:', typeof never);
